### ISSUE TITLE
[Installer] Add MPCC host as system in system inventory

### ISSUE THREAD

**Issue by biondogs** [mprov-ng/mprov_control_center#101]
Self explanatory, 

 but also we should include some other default things like LDAP, and ansible things that seem valuable even if only as default examples.

**Comment by jhujasonw** [comment]
mpcc host system now adds itself as of https://github.com/mprov-ng/mprov_control_center/commit/b774ced88f6c2fea0502646fab2bae38d5c2f4b0

Other default things added in previous commits.

**Comment by jhujasonw** [comment]
Will need to discuss if LDAP management should be added by default by the installer or if that should be an addon by the end user.  I am starting to think it should be a default but we can open a separate ticket for that if we decide that is the case.
