### ISSUE TITLE
Add Name of cluster to Banner Bar

### ISSUE THREAD

**Issue by biondogs** [mprov-ng/mprov_control_center#114]
Name / IP / Whatever /Color maybe.. We need to know where we are when making changes!!

**Comment by jhujasonw** [comment]
Color can be set by changing the `navbar` under `JAZZMIN_UI_TWEAKS` in the `settings.py`  Another commit is coming that will automatically set `JAZZMIN_SETTINGS.name` to the `socket.gethostname()` of the machine.  This can be also changed by the admin if they don't want to use the hostname by editing the `settings.py` file.
