### ISSUE TITLE
Live updating Search bar for systems page

### ISSUE THREAD

**Issue by biondogs** [mprov-ng/mprov_control_center#143]
Ajax style search bar that does a live filter thing with out a page reload would be SUPER Nice .. Or just a regular search bar if the former is a huge pain.

**Comment by jhujasonw** [comment]
search bar added but leaving this open for live update investigating.

**Comment by jhujasonw** [comment]
It would appear that most of the admin theming appears to not support live searches, probably for a reason.  I think I might close this for now and revist the live search if I find an admin theme that supports it.
